version: "3.8"
services:
  web: 
    build: ./gitgud-san-benito/front
    ports:
      - "8080:8080"
  django:
    restart: always
    build: ./gitgud-san-benito/back
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8000:8000"
    networks:
      - djangonetwork
    links:
      - db:db
    depends_on:
      - db
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER = postgres
      - POSTGRES_PASSWORD = postgres
      - POSTGRES_HOST_AUTH_METHOD = trust
      - POSTGRES_HOST = db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    networks:
      - djangonetwork
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL = admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD = "admin"
    ports:
      - "5051:80"
    depends_on:
      - postgres
networks:
  djangonetwork:
    driver: bridge