version: "3.8"
services:
  web: 
    build: ./gitgud-san-benito/front
    ports:
      - "8080:8080"
  django:
    build: ./gitgud-san-benito/back
    command: "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=post
      - POSTGRES_HOST_AUTH_METHOD=trust
      
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    expose:
      - "5432"
    
    ports:
      - 5432:5432
    volumes:
    - /var/lib/postgresql/data

 
