version: "3.8"
services:
  web: 
    build: ./gitgud-san-benito/front
    ports:
      - 8080:8080
  django:
    build: ./gitgud-san-benito/back
    ports:
      - 8000:8000
    depends_on:
      - postgres
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=post
    volumes:
    - data:/var/lib/postgresql/data

 
