version: "3.8"
services:
  web: 
    build: ./gitgud-san-benito/front
    ports:
      - "8080:8080"
  
  django:
    restart: always
    build: ./gitgud-san-benito/back
    environment:
      - APP_PORT=8000
    ports:
      - "8000:8000"
    links:
      - db:db
    depends_on:
      - db
  db:
    
    
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    