# Generated by Django 4.2.6 on 2023-11-08 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carabinero',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=255, null=True)),
                ('apellidos', models.CharField(max_length=255, null=True)),
                ('fecha_de_nacimiento', models.DateField(default=django.utils.timezone.now)),
                ('rango', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acusado', models.CharField(max_length=12)),
                ('descripcion', models.CharField(max_length=12)),
                ('foto', models.ImageField(null=True, upload_to='fotos/')),
                ('video', models.FileField(null=True, upload_to='videos/')),
            ],
        ),
        migrations.CreateModel(
            name='Infraccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('gravedad', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('acusado', models.CharField(max_length=12)),
                ('acusante', models.CharField(max_length=12)),
                ('patente_auto', models.CharField(max_length=10)),
                ('multa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Infractor',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=255, null=True)),
                ('apellidos', models.CharField(max_length=255, null=True)),
                ('fecha_de_nacimiento', models.DateField(default=django.utils.timezone.now)),
                ('numero_de_infracciones', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=255, null=True)),
                ('apellidos', models.CharField(max_length=255, null=True)),
                ('fecha_de_nacimiento', models.DateField(default=django.utils.timezone.now)),
                ('area_de_inspeccion', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=255, null=True)),
                ('apellidos', models.CharField(max_length=255, null=True)),
                ('fecha_de_nacimiento', models.DateField(default=django.utils.timezone.now)),
                ('experiencia_judicial', models.PositiveIntegerField(default=0)),
                ('username', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
