# Generated by Django 4.2.6 on 2023-10-24 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sanbenito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acusado', models.IntegerField()),
                ('descripcion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Infraccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateField()),
                ('gravedad', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('acusado', models.CharField(max_length=9)),
                ('acusante', models.CharField(max_length=9)),
                ('patente_auto', models.CharField(max_length=10)),
                ('multa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Infractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_infracciones', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_de_inspeccion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Juez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia_judicial', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('nombres', models.CharField(max_length=255, null=True)),
                ('apellidos', models.CharField(max_length=255, null=True)),
                ('rut', models.IntegerField(max_length=9, primary_key=True, serialize=False)),
                ('fecha_de_nacimiento', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='carabinero',
            name='nombre',
        ),
        migrations.AddField(
            model_name='carabinero',
            name='rango',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
