# Generated by Django 4.2.6 on 2023-10-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanbenito', '0004_delete_persona_remove_carabinero_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carabinero',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
