# Generated by Django 4.2.6 on 2023-10-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanbenito', '0005_alter_carabinero_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='acusado',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='descripcion',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='acusado',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='infraccion',
            name='acusante',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='infractor',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='juez',
            name='rut',
            field=models.CharField(max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
