# Generated by Django 4.2.6 on 2023-11-08 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanbenito', '0008_carabinero_password_carabinero_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carabinero',
            name='password',
        ),
        migrations.RemoveField(
            model_name='carabinero',
            name='username',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='password',
        ),
        migrations.RemoveField(
            model_name='inspector',
            name='username',
        ),
        migrations.RemoveField(
            model_name='juez',
            name='password',
        ),
        migrations.RemoveField(
            model_name='juez',
            name='username',
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
