# Generated by Django 4.2.7 on 2023-11-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanbenito', '0010_carabinero_password_carabinero_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
