# Generated by Django 4.2.7 on 2023-11-08 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sanbenito', '0012_appuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
